## Important concets to discuss

* Why Jupyter Notebooks are not a production grade environment 
* How to make a proper environment setup
    * Anaconda
    * virtualenv
    * colabs
* Basic Data types
    * int, floats, booleans
* Data Structures
    * lists
    * dictionaries
    * tuples
* Functions
    * return
* Libraries 
    * numpy 
 

## Python basics

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**

In [1]:
7 ** 4

2401

** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **

In [2]:
s = 'Hi there Sam!'

In [3]:
s.split()

['Hi', 'there', 'Sam!']

In [3]:
s.split()

['Hi', 'there', 'dad!']

** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742
print(f'The diameter of {planet} is {diameter} kilometers')

The diameter of Earth is 12742 kilometers


In [6]:
print(f'The diameter of {planet} is {diameter} kilometers')

The diameter of Earth is 12742 kilometers.


** Given this nested list, use indexing to grab the word "hello" **

In [9]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [13]:
lst[3][1][2][0]

'hello'

** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [21]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**

In [30]:
def domain_get(email):
    
    return email.split('@')[1]

In [31]:
domain_get('user@domain.com')

'domain.com'

** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **

In [28]:
def find_dog(string):
    return 'dog' in string or 'Dog' in string

In [29]:
find_dog('Is there a Dog here?')

True

** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **

In [31]:
count_dog('This dog runs faster than the other dog dude!')

2

** Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**

    seq = ['soup','dog','salad','cat','great']

**should be filtered down to:**

    ['soup','salad']

In [34]:
seq = ['soup','dog','salad','cat','great']

['soup', 'salad']

### Final Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **

In [36]:
def caught_speeding(speed, is_birthday):
    pass

In [42]:
caught_speeding(81, True)

'Small Ticket'

In [43]:
caught_speeding(81, False)

'Big Ticket'

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

#### Import NumPy as np

#### Create an array of 10 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

array([0.40403684])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 8.44272486e-01, -1.50719493e+00,  1.85766191e+00,  1.47057999e-01,
       -8.09334948e-02,  6.07909235e-01,  2.06256552e+00, -1.92108575e-03,
       -2.60509183e-01,  3.24217270e-01, -6.15926355e-01, -1.54227723e+00,
       -1.35884630e+00, -3.94243657e-01, -8.04293623e-01, -9.38197482e-01,
        8.00749278e-02, -3.34192448e-01, -2.16267047e+00, -2.52790087e-01,
        1.40489314e+00, -1.13212378e-01,  1.22315041e+00, -5.18170941e-01,
        1.25439793e+00])

#### Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [57]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

matrix([[12, 13, 14, 15],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [75]:
# get the last element of the second row

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Some more exercises

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

#### How to get the dates of yesterday, today and tomorrow?

#### Create random vector of size 10 and replace the maximum value by 0